# Generated by Django 4.0.5 on 2022-07-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
